export const theme = {
  colors: {
    primary: "#0061a5",
    "on-primary": "#ffffff",
    "primary-container": "#0d99ff",
    "on-primary-container": "#002f55",
    secondary: "#5f5e5e",
    "on-secondary": "#ffffff",
    "secondary-container": "#e4e2e1",
    "on-secondary-container": "#656464",
    tertiary: "#545f72",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#8b96ab",
    "on-tertiary-container": "#242f40",
    error: "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#93000a",
    background: "#fcf9f8",
    "on-background": "#1b1c1c",
    surface: "#fcf9f8",
    "on-surface": "#1b1c1c",
    "surface-variant": "#e4e2e1",
    "on-surface-variant": "#3f4753",
    outline: "#707884",
    "outline-variant": "#bfc7d5",
    "inverse-surface": "#303030",
    "inverse-on-surface": "#f3f0f0",
    "inverse-primary": "#9fcaff",
    "surface-dim": "#dcd9d9",
    "surface-bright": "#fcf9f8",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f6f3f2",
    "surface-container": "#f0eded",
    "surface-container-high": "#eae7e7",
    "surface-container-highest": "#e4e2e1",
  },
  fontFamily: {
    headline: ["Inter", "sans-serif"],
    body: ["Inter", "sans-serif"],
    label: ["Inter", "sans-serif"],
  },
  borderRadius: {
    default: "0.125rem",
    lg: "0.25rem",
    xl: "0.5rem",
    full: "0.75rem",
  },
};
