create table if not exists public.bookmarks_news (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  news_id uuid not null references public.defense_news(id) on delete cascade,
  constraint bookmarks_news_pkey primary key (id),
  constraint bookmarks_news_user_news_key unique (user_id, news_id)
) tablespace pg_default;

alter table public.bookmarks_news
  alter column user_id drop default,
  alter column news_id drop default,
  alter column user_id set not null,
  alter column news_id set not null;

alter table public.bookmarks_news
  drop constraint if exists bookmarks_news_user_id_fkey,
  add constraint bookmarks_news_user_id_fkey
    foreign key (user_id) references public.profiles(id) on delete cascade;

alter table public.bookmarks_news
  drop constraint if exists bookmarks_news_news_id_fkey,
  add constraint bookmarks_news_news_id_fkey
    foreign key (news_id) references public.defense_news(id) on delete cascade;

create unique index if not exists idx_bookmarks_news_user_news
  on public.bookmarks_news using btree (user_id, news_id) tablespace pg_default;

create index if not exists idx_bookmarks_news_user_id
  on public.bookmarks_news using btree (user_id) tablespace pg_default;

create index if not exists idx_bookmarks_news_news_id
  on public.bookmarks_news using btree (news_id) tablespace pg_default;

alter table public.bookmarks_news enable row level security;

drop policy if exists "bookmarks_news: own select" on public.bookmarks_news;
create policy "bookmarks_news: own select"
  on public.bookmarks_news for select
  using (auth.uid() = user_id);

drop policy if exists "bookmarks_news: own insert" on public.bookmarks_news;
create policy "bookmarks_news: own insert"
  on public.bookmarks_news for insert
  with check (auth.uid() = user_id);

drop policy if exists "bookmarks_news: own delete" on public.bookmarks_news;
create policy "bookmarks_news: own delete"
  on public.bookmarks_news for delete
  using (auth.uid() = user_id);
