-- ============================================================
-- Modern Sentinel - Community Schema
-- Supabase 대시보드 SQL Editor에서 실행하세요.
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. profiles 테이블 (auth.users와 1:1, 서비스 내 회원 정보)
-- ────────────────────────────────────────────────────────────
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  nickname    text not null unique,
  rank        text,                        -- 계급 (선택)
  unit        text,                        -- 소속부대 (선택)
  avatar_url  text,                        -- OAuth 프로필 이미지
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.profiles is '서비스 내 사용자 프로필 (auth.users와 1:1)';

-- RLS 활성화
alter table public.profiles enable row level security;

-- 누구나 프로필 조회 가능
create policy "profiles: 전체 조회 허용"
  on public.profiles for select
  using (true);

-- 본인 프로필만 생성 가능
create policy "profiles: 본인만 생성"
  on public.profiles for insert
  to authenticated
  with check ((select auth.uid()) = id);

-- 본인 프로필만 수정 가능
create policy "profiles: 본인만 수정"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id)
  with check ((select auth.uid()) = id);


-- ────────────────────────────────────────────────────────────
-- 2. community_posts 테이블 (커뮤니티 게시글)
-- ────────────────────────────────────────────────────────────
create table if not exists public.community_posts (
  id          uuid primary key default gen_random_uuid(),
  post_number bigint generated by default as identity unique,
  author_id   uuid not null references public.profiles(id) on delete cascade,
  title       text not null,
  content     text not null,
  category    text not null default 'general'
                check (category in ('general', 'question', 'info')),
  views       integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.community_posts is '커뮤니티 게시글';
comment on column public.community_posts.post_number is '커뮤니티 게시판 고유 번호';
comment on column public.community_posts.category is 'general=자유게시판, question=질문게시판, info=정보공유';

-- RLS 활성화
alter table public.community_posts enable row level security;

-- 목록/검색/권한 체크 성능 최적화용 인덱스
create index if not exists community_posts_author_id_idx
  on public.community_posts (author_id);

create index if not exists community_posts_category_post_number_idx
  on public.community_posts (category, post_number desc);

-- 누구나 게시글 조회 가능 (비로그인 포함)
create policy "posts: 전체 조회 허용"
  on public.community_posts for select
  using (true);

-- 로그인한 사용자만 게시글 작성 가능
create policy "posts: 인증 사용자만 작성"
  on public.community_posts for insert
  to authenticated
  with check ((select auth.uid()) = author_id);

-- 본인 게시글만 수정 가능
create policy "posts: 본인만 수정"
  on public.community_posts for update
  to authenticated
  using ((select auth.uid()) = author_id)
  with check ((select auth.uid()) = author_id);

-- 본인 게시글만 삭제 가능
create policy "posts: 본인만 삭제"
  on public.community_posts for delete
  to authenticated
  using ((select auth.uid()) = author_id);


-- ────────────────────────────────────────────────────────────
-- 3. community_comments 테이블 (게시글 댓글, 단일 레벨)
-- ────────────────────────────────────────────────────────────
create table if not exists public.community_comments (
  id          uuid primary key default gen_random_uuid(),
  post_id     uuid not null references public.community_posts(id) on delete cascade,
  author_id   uuid not null references public.profiles(id) on delete cascade,
  content     text not null,
  created_at  timestamptz not null default now()
);

comment on table public.community_comments is '커뮤니티 게시글 댓글 (단일 레벨, 대댓글 없음)';

-- RLS 활성화
alter table public.community_comments enable row level security;

create index if not exists community_comments_post_id_created_at_idx
  on public.community_comments (post_id, created_at);

create index if not exists community_comments_author_id_idx
  on public.community_comments (author_id);

-- 누구나 댓글 조회 가능
create policy "comments: 전체 조회 허용"
  on public.community_comments for select
  using (true);

-- 로그인한 사용자만 댓글 작성 가능
create policy "comments: 인증 사용자만 작성"
  on public.community_comments for insert
  to authenticated
  with check ((select auth.uid()) = author_id);

-- 본인 댓글만 삭제 가능
create policy "comments: 본인만 삭제"
  on public.community_comments for delete
  to authenticated
  using ((select auth.uid()) = author_id);


-- ────────────────────────────────────────────────────────────
-- 4. 조회수 증가 헬퍼 함수
--    security definer: RLS를 우회하여 views 컬럼만 증가
-- ────────────────────────────────────────────────────────────
create or replace function public.increment_post_views(p_post_id uuid)
returns void
language sql
security definer
as $$
  update public.community_posts
  set views = views + 1
  where id = p_post_id;
$$;

comment on function public.increment_post_views is '게시글 조회수 1 증가 (RLS 우회, 인증 불필요)';


-- ────────────────────────────────────────────────────────────
-- 5. updated_at 자동 갱신 트리거 (posts)
-- ────────────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_posts_updated_at on public.community_posts;
create trigger trg_posts_updated_at
  before update on public.community_posts
  for each row execute function public.set_updated_at();

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();


-- ────────────────────────────────────────────────────────────
-- 6. 검색 성능 최적화 (ILIKE 대응)
--    title/content 검색은 trigram 인덱스로 가속
-- ────────────────────────────────────────────────────────────
create extension if not exists pg_trgm;

create index if not exists community_posts_title_trgm_idx
  on public.community_posts using gin (title gin_trgm_ops);

create index if not exists community_posts_content_trgm_idx
  on public.community_posts using gin (content gin_trgm_ops);


-- ────────────────────────────────────────────────────────────
-- 7. 완료 확인용 쿼리 (선택)
-- ────────────────────────────────────────────────────────────
-- select table_name from information_schema.tables
-- where table_schema = 'public'
--   and table_name in ('profiles', 'community_posts', 'community_comments');
